// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace OficinarBackEnd.Models;

public partial class PecasCarro
{
    public int Id { get; set; }

    public int Quantidade { get; set; }

    public string PartNumber { get; set; }

    public string Descricao { get; set; }

    public DateTime? DataCriacao { get; set; }

    public DateTime? DataModificacao { get; set; }
}