// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace OficinarCommon.Models;

public partial class Agendamento
{
    public int Id { get; set; }

    public int? IdCliente { get; set; }

    public DateTime DataHoraAgendamento { get; set; }

    public DateTime? DataCriacao { get; set; }

    public DateTime? DataModificacao { get; set; }

    public virtual ICollection<AgendamentoServico> AgendamentoServicos { get; set; } = new List<AgendamentoServico>();

    public virtual Cliente IdClienteNavigation { get; set; }
}