// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace OficinarCommon.Models;

public partial class AgendamentoServico
{
    public int Id { get; set; }

    public int? IdAgendamento { get; set; }

    public int? IdServico { get; set; }

    public DateTime? DataCriacao { get; set; }

    public DateTime? DataModificacao { get; set; }

    public virtual Agendamento IdAgendamentoNavigation { get; set; }

    public virtual Servico IdServicoNavigation { get; set; }
}