// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace OficinarCommon.Models;

public partial class Cliente
{
    public int Id { get; set; }

    public string Nome { get; set; }

    public string Cpf { get; set; }

    public string Endereco { get; set; }

    public DateOnly? Aniversario { get; set; }

    public DateTime? DataCriacao { get; set; }

    public DateTime? DataModificacao { get; set; }

    public virtual ICollection<Agendamento> Agendamentos { get; set; } = new List<Agendamento>();
}